# letsencrypt
letsencrypt_email: kurrawongai@gmail.com
domain_name: gsq-prez.dev.kurrawong.ai,api.gsq-prez.dev.kurrawong.ai

# container images
prez_ui_image: ghcr.io/kurrawong/gsq-prez-ui:git-main-2890bbef
prez_image: ghcr.io/rdflib/prez:3.0.9
fuseki_image: ghcr.io/kurrawong/fuseki-geosparql:git-main-23a3a84d

# a boolean value to control whether fuseki is accessible publicly via nginx
nginx_expose_fuseki: true

# prez ui settings
enabled_prezs: SpacePrez,VocPrez
prez_api_base_url: https://api.gsq-prez.dev.kurrawong.ai

# swapfile
swap_file_path: /swapfile
# Use any of the following suffixes
# c=1
# w=2
# b=512
# kB=1000
# K=1024
# MB=1000*1000
# M=1024*1024
# xM=M
# GB=1000*1000*1000
# G=1024*1024*1024
swap_file_size: 4G
swappiness: 1
